### ISSUE TITLE
未知报错

### ISSUE THREAD

**Issue by Wuyu-byte** [Mercer-Su/Rice_Yolov8_Optimization-_And_AI-assisted#1]
C:\Users\Relat\.conda\envs\Rice\lib\site-packages\ultralytics\nn\tasks.py:732: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the defa
ult pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#u
ntrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitra
ry objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  ckpt = torch.load(file, map_location="cpu")
WARNING ⚠️ weights\best.pt appears to require 'einops', which is not in ultralytics requirements.
AutoInstall will run now for 'einops' but this feature will be removed in the future.
Recommend fixes are to train a new model using the latest 'ultralytics' package or to run a command with an official YOLOv8 model, i.e. 'yolo predict model=yolov8n.pt'
requirements: Ultralytics requirement ['einops'] not found, attempting AutoUpdate...
requirements: ❌ AutoUpdate skipped (offline)
C:\Users\Relat\.conda\envs\Rice\lib\site-packages\ultralytics\nn\tasks.py:752: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the defa
ult pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#u
ntrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitra
ry objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  ckpt = torch.load(file, map_location="cpu")
2024-12-24 21:00:27.833 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\Relat\.conda\envs\Rice\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 584, in _run_script
    exec(code, module.__dict__)
  File "E:\Rice_Yolov8_Optimization-_And_AI-assisted\app.py", line 602, in <module>
    main()
  File "E:\Rice_Yolov8_Optimization-_And_AI-assisted\app.py", line 102, in main
    predict = infer_uploaded_image(confidence, model)
NameError: name 'model' is not defined

**Comment by Mercer-Su** [comment]
我没有办法复现出来， 看报错提示是没有模型
